### ISSUE TITLE
Error: Cannot find module 'normalize-text'

### ISSUE THREAD

**Issue by soullivaneuh** [rayfoss/feathers-nedb-fuzzy-search#3]
Complete stack:

```
Error: Cannot find module 'normalize-text'
Require stack:
- /home/sullivan/project/node_modules/feathers-nedb-fuzzy-search/index.js
- /home/sullivan/project/src/services/rides/rides.hooks.ts
- /home/sullivan/project/src/services/rides/rides.service.ts
- /home/sullivan/project/src/services/index.ts
- /home/sullivan/project/src/app.ts
- /home/sullivan/project/src/seed.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/sullivan/project/node_modules/feathers-nedb-fuzzy-search/index.js:2:33)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module._compile (/home/sullivan/project/node_modules/source-map-support/source-map-support.js:541:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Object.nodeDevHook [as .js] (/home/sullivan/project/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
```

The `normalize-text` should be declared as a dependency of your project.

**Comment by soulofmischief** [comment]
@soullivaneuh I've submitted a PR (#6) and am currently hosting the package under my own scope until the PRs are accepted.

**Comment by FossPrime** [comment]
What are you using as package manager? Pnpm, yarn? Just to make sure I test with it

**Comment by soulofmischief** [comment]
@rayfoss personally I'm using yarn, but this issue exists with both npm and yarn. normalize-text needs to be a regular dependency instead of a dev dependency, as per my PR
